2019-04-18 18:36:01.509901: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-04-18 18:36:01.521710: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2194840000 Hz
2019-04-18 18:36:01.524229: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x4e7e7f0 executing computations on platform Host. Devices:
2019-04-18 18:36:01.524265: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
E0418 18:36:01.527079663  146190 server_chttp2.cc:40]        {"created":"@1555630561.526947396","description":"No address added out of total 1 resolved","file":"external/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":349,"referenced_errors":[{"created":"@1555630561.526942334","description":"Failed to add any wildcard listeners","file":"external/grpc/src/core/lib/iomgr/tcp_server_posix.cc","file_line":324,"referenced_errors":[{"created":"@1555630561.52019-04-18 18:36:02.429826: W tensorflow/core/kernels/conditional_accumulator_base.cc:45] Attempt to set current_global_step_ to smaller value: current_global_step_ = 5501 >= 0 = new_global_step.
2019-04-18 18:36:02.429826: W tensorflow/core/kernels/conditional_accumulator_base.cc:45] Attempt to set current_global_step_ to smaller value: current_global_step_ = 5501 >= 0 = new_global_step.
created":"@1555630561.526941617","description":"Unable to configure socket","fd":5,"file":"external/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":217,"referenced_errors":[{"created":"@1555630561.526938173","description":"OS Error","errno":98,"file":"external/grpc/src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]}]}]}
2019-04-18 18:36:01.527151: E tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:466] Unknown: Could not start gRPC server
Traceback (most recent call last):
  File "distributed_sync_LR.py", line 46, in <module>
    server = tf.train.Server(clusterinfo, job_name=FLAGS.job_name, task_index=FLAGS.task_index)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/server_lib.py", line 148, in __init__
    self._server = c_api.TF_NewServer(self._server_def.SerializeToString())
tensorflow.python.framework.errors_impl.UnknownError: Could not start gRPC server
